### ISSUE TITLE
Update codebase and document how to deploy on a data site

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/docker-elk#1]
The idea is to update this code base to include the customization needed to run this ELK stack on an NLP Data Hosting site. I think that @thomasyu888 added a plugin to capture logs generated by NLP tools evaluated on the same EC2 as where the ELK stack is running.

@thomasyu888 Is that correct? If yes, can you open a PR to add the plugin that you use so that it's automatically active when deploying this ELK stack?

**Comment by thomasyu888** [comment]
@tschaffter Theres no custom code that needs to be added. I just followed instructions here: https://github.com/nlpsandbox/docker-elk/tree/develop/extensions/logspout.

We technically can just lead people to the original ELK repo.

**Comment by tschaffter** [comment]
Documented in the controller repository
